### ISSUE TITLE
6.12.1 with java 17

### ISSUE THREAD

**Issue by lpdevit** [dynamicreports/dynamicreports#124]
Hi @jan-moxter 

I have a big software built on dynamicreports 6.12.1 (the latest version available in maven, more than 2 years old).
I see that it depends on jasperreports 6.12.2 (more than 3 years old!), which depends on com.lowagie.itext 2.1.7.js7.
What's preventing me to update to Java 17 (with jakarta.* namespace)?

I see that development branch depends on jasperreports 6.20.6 (latest version available; [according to its owner, it's shipped with Java 17](https://community.jaspersoft.com/questions/1217821/does-jaspersoft-studio-6191-or-later-support-java-17); [they're also saying that release 7 is months away](https://community.jaspersoft.com/questions/1218921/jasper-reports-library-v7-availability)); since version [6.20.1](https://github.com/TIBCOSoftware/jasperreports/releases/tag/6.20.1), they replaced itext with OpenPDF.

Is it possible to have a new version of dynamicreports using updated dependencies? How can I use it in production?

Thank you for your help!

**Comment by jan-moxter** [comment]
Hello, in my personal projects I am using the snapshot version, but that does not guarantee any stability so therefore might not be the solution for all. 
The only thing hindering a new release   is that I do not have any more feedback from other users if the new versions a actually working fine.... everything is fine in my projects, all reports work fine.
Snapshot is deployed automatically to sonatype

**Comment by lpdevit** [comment]
Thank you! Tomorrow I can test your snapshot version in my big production project (it has extensive use of dynamicreports and other pdf libraries). Can you help me with setting up my pom.xml? Which dependency do I have to use?

**Comment by lpdevit** [comment]
Does 6.20.0-SNAPSHOT only works with Java 17 or is it compatible also with JDK 8?

**Comment by jan-moxter** [comment]
dependency in POM:

        <dependency>
            <groupId>net.sourceforge.dynamicreports</groupId>
            <artifactId>dynamicreports-core</artifactId>
            <version>6.20.0-SNAPSHOT</version>
          </dependency>
          
 add repo in settings.xml         
 e.g.
                <repository>
                    <id>oss_snapshot</id>
                    <releases>
                        <enabled>false</enabled>
                        <checksumPolicy>warn</checksumPolicy>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                        <checksumPolicy>warn</checksumPolicy>
                    </snapshots>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                    <layout>default</layout>
                </repository>
              
              
  now it should search dynamicreports snapshots in the sonatype repo

**Comment by lpdevit** [comment]
ok I'll try and let you know asap, I'll check different JDK versions (8 and 17).
What versions of dynamicreports-adhoc and dynamicreports-googlecharts do I have to use?
Also, do I need dynamicreports-parent or -core is enough?

**Comment by jan-moxter** [comment]
It is compiled with 17 so it would cause problems. There should not be any specific code written in Java-17 only

**Comment by jan-moxter** [comment]
I was ignoring during the upgrade    dynamicreports-adhoc and dynamicreports-googlecharts..,. And was actually thinking on deprecating them, due to now seeing any usage of them at all. 
So using only the core would be enough. My idea was only work on the core in the future and only if I get enough feedbakc that this libraries are used maybe upgrade them also

**Comment by lpdevit** [comment]
> I was ignoring during the upgrade dynamicreports-adhoc and dynamicreports-googlecharts..,. And was actually thinking on deprecating them, due to now seeing any usage of them at all. So using only the core would be enough. My idea was only work on the core in the future and only if I get enough feedbakc that this libraries are used maybe upgrade them also

I'm pretty sure I use them in my prj but I'll double check tomorrow. Thank you for your help!

**Comment by lpdevit** [comment]
Hi @jan-moxter
I can confirm that I don't use -adhoc and -googlecharts in my project (they were in pom.xml but never used).
I upgraded to JasperReports 6.20.6 and OpenPDF (instead of iText 2).
I tested my project and my reports with dynamicreports 6.20.0-SNAPSHOT and it works flawlessly!!!
As you said above, I had to move from JDK 8 to 17: since you stated that "There should not be any specific code written in Java-17 only", is it possible to make 6.20.0 compatible both with Java 8 and Java 17+?
Also, are you planning to release a stable version of that 6.20.0 to Maven Central?
Thank you so much for your help, this project is amazing!

**Comment by jan-moxter** [comment]
Ok, nice to hear, ... planing to release it the upcoming week

**Comment by lpdevit** [comment]
Hi @jan-moxter do you have any news about 6.20.0 release on Maven (compatible both with Java 8 and Java 17+)? Thank you so much for your help :)

**Comment by jan-moxter** [comment]
Hello, sorry had a heavy week, but i am sure that I can do it the upcoming week :+1: I

**Comment by celyo** [comment]
Hello @jan-moxter,

Jasper Reports 6.21.3 (which is the latest version from 6.x series at the moment of writing this comment) requires Java 8 and can be run on Java 11. Is there any specific reason Dynamic Reports to require Java 17? AFAIK there is no source code compatibility reason to jump directly to Java 17. I even managed to compile the library locally with Java 11 (not tested with Java 8). So it looks like it's just a matter of releasing.

It would be really great if a new version of Dynamic Reports could be provided, which is compatible with Java 11 at least.
