### ISSUE TITLE
``Default#getTextFieldTextAdjust`` always returns ``null``

### ISSUE THREAD

**Issue by AB-xdev** [dynamicreports/dynamicreports#180]
So there is an error in dynamicreports where ``getTextFieldTextAdjust`` ALWAYS returns ``null``:
https://github.com/dynamicreports/dynamicreports/blob/3f80c6f7555a52761e751767783117fd5892a826/dynamicreports-core/src/main/java/net/sf/dynamicreports/report/defaults/Default.java#L1065

We addressed this problem in our fork [here](https://github.com/xdev-software/dynamicreports-core-for-grid-exporter/commit/eedeb6306e7bcd0468cfac40e3ff44445ec4687a), feel free to backport the fix

**Comment by jan-moxter** [comment]
fixed for 7
