### ISSUE TITLE
Make the project buildable

### ISSUE THREAD

**Issue by jan-moxter** [dynamicreports/dynamicreports#2]
In the moment the parent pom is not part of this project. But it influences all the major used libraries. 

i think it might be a good idea as a first step to rebuild the parent pom so that all part can be build locally using standard maven

**Comment by ghacupha** [comment]
On it

**Comment by ghacupha** [comment]
Okay. So now the builds are running just fine on my machine (windows), but on travis they fail. I guess it's because of use of Arial font. Will check on it later

**Comment by jan-moxter** [comment]
Man, you are fast 😊 Awesome.


Do not fear to assign some work to me also... I did not mean to indicate that you have to do all the work

Really like your README

Jan

________________________________

**Comment by jan-moxter** [comment]
I can confirm that build works on linux :-) now

**Comment by jan-moxter** [comment]
Got the build for travis working. I made a pull request for it

**Comment by ghacupha** [comment]
Thanks. Thought I'd give it my best. We still have work on the contributing
template, it being adopted from atom project still has a lot of editing to
do. Would love to see your ideas on the build too.

Edwin

**Comment by ghacupha** [comment]
Okay I just thought of something else. In a commit I retained the Arial font, and it just occurred to me that if you were to download the source, it would not work on a linux box, since one has to run the installation script. I will see if I could have maven run your script during its lifecycle

**Comment by ghacupha** [comment]
Done. Added the installation into a profile. So now when you are in linux, you could run tests like: mvn test -Pms-fonts. Your thoughts?

**Comment by jan-moxter** [comment]
I think we should not add a script to install the ms-fonts add all. The scripts differ to much depending on the Linux version. It is necessary to get the tests run during the tests on Travis, but if someone is pulling the code and wants to run the tests, it is up to this person to decide if he wants to install them and how this should be done.
Building is possible without the ms-fonts by skipping the tests. An explanation on wiki like 'if you want to run the tests ms-fonts must be installed' should really be enougth

**Comment by ghacupha** [comment]
Okay. I will that branch alone. I will now see why the examples are failing, also as part of making the project buildable. Kindly advise if you see something on your end, and once again thank you for your valuable contribution
