### ISSUE TITLE
Daylight Time Saving

### ISSUE THREAD

**Issue by 0BuRner** [dynamicreports/dynamicreports#32]
Hello,

How can I manage daylight time saving using dynamicreports ?

I tried to set a parameter via the code : 
`report.setParameter(JRParameter.REPORT_TIME_ZONE, TimeZone.getTimeZone("Europe/Brussels"));`
or via properties :
`net.sf.jasperreports.pattern.timezone=System`

I'm using a ChartCustomizer to set the unit :
```
final DateFormat formatter = new SimpleDateFormat("HH", locale);
final DateTickUnit dateTickUnit = new DateTickUnit(DateTickUnitType.HOUR, 1, formatter);
((DateAxis) chart.getXYPlot().getDomainAxis()).setTickUnit(dateTickUnit);
```

## Expected Behavior
On 28th October 2018 :
Hour | Value
00h - A
01h - B
02h - C
02h - D
03h - E
04h - F
...

## Current Behavior
On 28th October 2018 :
Hour | Value
00h - A
01h - B
02h - C
03h - D
04h - E
05h - F
...

## Context
I'm trying to display charts to the user in a correct manner regarding the daylight saving time.

## Your Environment
Windows 10
Java 1.8
DynamicReports 5.0.0
Data TimeZone : UTC
User TimeZone : Europe/Brussels

**Comment by jan-moxter** [comment]
Normally that would just be passed on to JasperReport itself. But I will take look into it

**Comment by 0BuRner** [comment]
I finally found out what was the problem.
I set the timezone on the SimpleDateFormat and it works !
Thanks anyway
