### ISSUE TITLE
Add datasource dependent hyperlink to column

### ISSUE THREAD

**Issue by jPan-SOP** [dynamicreports/dynamicreports#46]
Hello,
I am not sure if this is the right place for questions like this, but since this seems to be the only active place concerning DynamicReports, I hope somebody can help me. In this spirit: Thank you very much for keeping this project alive! 

I’ve been experimenting with the “GroupSubtotalReport” example (https://github.com/dynamicreports/dynamicreports/blob/development/dynamicreports-examples/src/main/java/net/sf/dynamicreports/examples/subtotal/GroupSubtotalReport.java) and would like to add hyperlinks to the table cells of the country column. The reference of the link should depend on the text in the cell, for example for the text “USA” the reference “https://www.google.com/search?q=USA“ should be assigned to the table cell. 

Is there any way to achieve this with the existing API or what would I need to modify to do so?
Thank you!

**Comment by jan-moxter** [comment]
Yes it is possible but it needs actually extending the underlying jasperreport. To get a link that will be rendered when exporting to html you would need to register an elementhandler ("net.sf.jasperreports.engine.export.DefaultElementHandlerBundle") and this must than be part of the report. That is quit some work but it can be archived. Depending on the complexity of the report and the flexibility required it can be easier to parse the generated html....

**Comment by jPan-SOP** [comment]
Thank you very much for your advice, I eventually solved it by assigning the static part of the link to the hyperlink of the column and fill in the dynamic part in the click handler, depending on the text in the cell.
