### ISSUE TITLE
Update JasperReport dependency to 6.8.0

### ISSUE THREAD

**Issue by jan-moxter** [dynamicreports/dynamicreports#47]
Your issue may already be reported!
Please search on the [issue track](https://github.com/dynamicreports/dynamicreports/issues) before creating one.

## Expected Behavior

Update JasperReport dependency to 6.8.0

## Current Behavior

Uses 6.7.0

## Your Environment

* Version used:
* Java version being used:
* Jasper library used if any other is being used in the project
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by szymongajek** [comment]
hello @jan-moxter  @ghacupha 
I hope the dynamicreports community is still active... If so I have prepared a PR for the issue.
