### ISSUE TITLE
Add Code Coverage Service

### ISSUE THREAD

**Issue by jan-moxter** [dynamicreports/dynamicreports#5]
## Expected Behavior
Add a Code Coverage Service to the build

## Current Behavior
No Code Coverage yet

## Possible Solution
I would propose to use [CodeCov](https://codecov.io/). I do use it currently on other projects and i like it. It does work good with a maven build on Travis-CI. 

But I am open to other services :-)

## Context
CodeCoverage does allow better development

**Comment by ghacupha** [comment]
I was thinking of coveralls, but only because I have seen other people use it but personally, I tried and failed. So if you know how CodeCov works, kindly advise

**Comment by jan-moxter** [comment]
I think i can. Will try it an keep you informed

**Comment by jan-moxter** [comment]
Done. It works on the branch code-coverage. The result can be seen on https://codecov.io/gh/dynamicreports/dynamicreports .. In the moment I only get 500 when I want to make a pull request here on github. Will try later again

**Comment by ghacupha** [comment]
I have seen the branch. Thanks load

**Comment by ghacupha** [comment]
I merged it onto main
