### ISSUE TITLE
Ring Chart support

### ISSUE THREAD

**Issue by rajild** [dynamicreports/dynamicreports#50]
Any option to add Ring Chart?

I tried using 

JFreeChart chart1 = ChartFactory.createRingChart( texttitle, data, islegend, tooltips, urls);
BufferedImage image = chart1.createBufferedImage(150,150);

report.addSummary(cmp.image(image))

But it is not in proper resolution.

**Comment by jan-moxter** [comment]
What do you mean with proper resolution?

**Comment by rajild** [comment]
The method I followed is,  Chart is exported as an image and this image is printed in the report (BufferedImage in this case).  Here resolution of the chart is not good as other charts in the report (like cht.pieChart)

[PieChart_RingChart_sample.pdf](https://github.com/dynamicreports/dynamicreports/files/3451251/PieChart_RingChart_sample.pdf)

[Sample and code.zip](https://github.com/dynamicreports/dynamicreports/files/3451261/Sample.and.code.zip)

Sample output and code attached for review if required.
