### ISSUE TITLE
Deployment fails due to Javadoc

### ISSUE THREAD

**Issue by jan-moxter** [dynamicreports/dynamicreports#51]
Your issue may already be reported!
Please search on the [issue track](https://github.com/dynamicreports/dynamicreports/issues) before creating one.

## Expected Behavior
mvn release:prepare works

## Current Behavior
fails to error during Javadoc creation

## Possible Solution
mvn javadoc:javadoc => clean javadoc until passes

## Steps to Reproduce (for bugs)
mvn javadoc:javadoc

## Your Environment
openjdk8

**Comment by ghacupha** [comment]
That one is on me. I made some major mistakes in earlier commits. Let me fix and advice.

**Comment by ghacupha** [comment]
New insights: The code generated by JAXB runtime has weak form formatting for javadoc with empty tags. That's why core module will have a million javadoc errors. Is there a way to except JAXB files from strict javadoc guidelines?

**Comment by ghacupha** [comment]
Okay javadoc is turning out to be more pedantic than I initially estimated. So this will take some time

**Comment by ghacupha** [comment]
I have seen the release 6.1.0, good job @jan-moxter
