### ISSUE TITLE
How can I support html elements in certain columns?

### ISSUE THREAD

**Issue by combinationofsymbols** [dynamicreports/dynamicreports#56]
I have certain columns that can have data containing html elements. I would like to support  at least some of them (mainly html tables) at least when exporting report as html, preferably when exporting as pdf as well.

Using markup.HTML simply removes the elements even when exporting as html. I've tried using GenericElements, which does allow inserting html into reports, but I can't figure out if it is possible to access data inside genericElementHtmlHandler implementation.

At minimum I would like to allow the column contents to pass through unaltered (i.e. without brackets getting encoded etc.).

**Comment by jan-moxter** [comment]
The aproach would have been to register an jasperreport extension
