### ISSUE TITLE
Add range to Xaxis?

### ISSUE THREAD

**Issue by tahaYassineM** [dynamicreports/dynamicreports#66]
I have faced a problem how to fix xaxis values. could I add a range to fix it?
![image](https://user-images.githubusercontent.com/12478367/81820807-96d11b80-9520-11ea-9d91-09ffed90ec33.png)

**Comment by jan-moxter** [comment]
Wow that is a lot of points on that axis :-) If you add only a range of points, it will seperate them more

**Comment by tahaYassineM** [comment]
How may I do that
Thanks for you reply.

**Comment by jan-moxter** [comment]
On net.sf.dynamicreports.design.base.chart.plot.DRDesignAxisPlot you can set the DRDesignAxisFormat

**Comment by jan-moxter** [comment]
You also con look here:
https://dynamicreports.readthedocs.io/en/latest/examples/chart/index.html

**Comment by tahaYassineM** [comment]
this is my code:

LineChartBuilder LineChart = cht.lineChart().customizers(new ChartCustomizer());

        LineChart.setTitle((String) config.get("title")).setStyle(columnTitleStyle);
        LineChart.setSubtitle((String) config.get("subtitle"));
        LineChart.setTitleFont(boldFont);
        LineChart.setShowValues((Boolean) config.get("showValues"));
        LineChart.setValuePattern((String) config.get("valuesPattern"));
        LineChart.setCategory(resolutionColumn);
        LineChart.setShowLegend((Boolean) config.get("showLegend"));
        LineChart.setLegendPosition(getLegendPosition((String) config.get("positionLegend")));
        tags.forEach(tag -> {
            LineChart.addSerie(cht.serie(tag));
        });

        LineChart.setCategoryAxisFormat(cht.axisFormat().setLabel("Resolution"));
        LineChart.setDataSource(dataSource1);

I didn't get how to implement DRDesignAxisFormat.

**Comment by jan-moxter** [comment]
Sorry that I was not able to help. I am not using currently this graph in any live code. Hope that you found a solution
