### ISSUE TITLE
How To repeat the footer in each page

### ISSUE THREAD

**Issue by tahaYassineM** [dynamicreports/dynamicreports#67]
I he faed another problem ho to set the footer in all pages.
this is the code of the example.
StyleBuilder style = stl.style(stl.pen1Point()).setTextAlignment(HorizontalTextAlignment.CENTER,
                    VerticalTextAlignment.MIDDLE);

            MultiPageListBuilder multiPageList = cmp.multiPageList();
            for (int i = 0; i < 20; i++) {
                TextFieldBuilder<String> textField = cmp.text("Title component " + (i + 1)).setFixedHeight(100).setStyle(style);
                multiPageList.add(textField);
            }

            try {
                report().setTemplate(Templates.reportTemplate).title(Templates.createHeaderComponent("MultiPageList"))
                        .summary(multiPageList).pageFooter(Templates.footerComponent)
                        .toPdf(export.pdfExporter("C:\\Users\\lordt\\OneDrive\\Bureau\\" + new Date().getTime() +".pdf"));
            } catch (DRException e) {
                e.printStackTrace();
            }

**Comment by jan-moxter** [comment]
You are using the the summary to simulate various pages. SUmmary normaly does not use the footer and headers. but it can be activated:

.summary(multiPageList).setSummaryWithPageHeaderAndFooter(true) .pageFooter(Templates.footerComponent)
