### ISSUE TITLE
Add isBlankWhenNull property control

### ISSUE THREAD

**Issue by EPluribusUnum** [dynamicreports/dynamicreports#69]
Hi!

Currently JRs isBlankWhenNull value is hard coded in DR : setBlankWhenNull(true) in ComponentTransform.java and StyleTransform.java.
It would be great to have the ability to control this value.

Because of the hard coded behaviour numeric null values are written to excel output as empty strings.
If the user want to add expression with arithmetic on these cells, the user gets #VALUE! errors/results from the expression. (SUM function does not care, but arithmetic operators do)

Thank You!

**Comment by jan-moxter** [comment]
Would you have the capability / interest / time to due a pull request for this kind of change?

**Comment by EPluribusUnum** [comment]
I have the interest, but unfortunately no capability & time.

**Comment by EPluribusUnum** [comment]
We have a pressure form a customer to fix this issue.
@jan-moxter , @ghacupha : Is there a way to finance this development?

**Comment by EPluribusUnum** [comment]
I upgraded to the latest DR + JR and my original problem was solved.

(numeric column null values was not expored right in xls/x, operations with null cells resulted in #VALUE)

**Comment by jan-moxter** [comment]
Nice to hear. Sorry of not being to helpful here :+1:
