### ISSUE TITLE
bug export to pdf, does not print all the contents of the column

### ISSUE THREAD

**Issue by maximspu** [dynamicreports/dynamicreports#78]
Good morning,

if I print a grid with a single column of fixed size containing the text "aaaaaaaaaaa bbbbbbbbbbbbb vvvvvvvvvvvvvvv ffffffff gggdfgegtrtyueee", the portion of text "gggdfgegtrtyueee" is not printed in the pdf file.
If I use the show command instead, the text is printed correctly.

Example:

import static net.sf.dynamicreports.report.builder.DynamicReports.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import net.sf.dynamicreports.jasper.builder.JasperReportBuilder;
import net.sf.dynamicreports.report.builder.style.FontBuilder;
import net.sf.dynamicreports.report.constant.LineStyle;
import net.sf.dynamicreports.report.exception.DRException;
import net.sf.jasperreports.engine.data.JRMapCollectionDataSource;
//import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
public class BugFixedColumnWidth {

	public BugFixedColumnWidth() {
		build();
	}
	private void build() {
		try {
			Collection<Map<String, ?>> datasource = new ArrayList<Map<String,?>>();
            
		  	HashMap<String,List<String>> data = new HashMap<String,List<String>>();
		  	List<String> comments = new ArrayList<String>();
		  	comments.add("aaaaaaaaaaa  bbbbbbbbbbbbb vvvvvvvvvvvvvvv ffffffff gggdfgegtrtyueee");
		  	data.put("comments",comments);
		  	datasource.add(data);
	        
		  	FontBuilder fontColumn= stl.font();
			fontColumn.setFontName("Serif");
			fontColumn.setFontSize(6);
			
			OutputStream output=null;
			try {
				output = new FileOutputStream("test.pdf");
			} catch (FileNotFoundException e1) {
				e1.printStackTrace();
			}
			
			JasperReportBuilder report =report()
			  .setColumnStyle(stl.style().setFont(fontColumn).setBorder(stl.pen((float)0.1,LineStyle.SOLID)).setPadding(2))
			  .columns(
			  	col.column("Descrizione",  "comments", type.listType()).setFixedWidth(112))
			  .setDataSource(new JRMapCollectionDataSource(datasource))
			  .toPdf(output);
		} catch (DRException e) {
			e.printStackTrace();
		}
	}
	public static void main(String[] args) {
		new BugFixedColumnWidth();
	}
}

PDF OUTPUT: ( .toPdf(output) )

![immagine](https://user-images.githubusercontent.com/74463405/99240525-e7417280-27fc-11eb-848f-68eb3167a679.png)

with the command .show () you get instead:

PREVIEW OUTPUT: ( .show() )

![immagine](https://user-images.githubusercontent.com/74463405/99240950-7c446b80-27fd-11eb-9862-324c091fd2bc.png)

Regards

**Comment by jan-moxter** [comment]
Could you please try adding TextAdjust

` col.column("Descrizione",  "comments", type.listType()).setFixedWidth(112).setTextAdjust(TextAdjust.STRETCH_HEIGHT)`

**Comment by maximspu** [comment]
Hi jan-moxter,

thanks but unfortunately it doesn't work anyway, there is no need for the .setTextAdjust method (TextAdjust.STRETCH_HEIGHT)) because it already does it by default. If I add this text to the previous text: "Thanks for your help" the printing works. It does not work when the width of the last row is equal to the size of the column.

Example

text: aaaaaaaaaaa bbbbbbbbbbbbb vvvvvvvvvvvvvvv ffffffff gggdfgegtrtyueee Thanks for your help

works

![immagine](https://user-images.githubusercontent.com/74463405/99856277-e73ccc00-2b88-11eb-9d2d-3ce0bbd799c8.png)

text: aaaaaaaaaaa  bbbbbbbbbbbbb vvvvvvvvvvvvvvv ffffffff gggdfgegtrtyueee

don't work

![immagine](https://user-images.githubusercontent.com/74463405/99856361-1e12e200-2b89-11eb-9441-08394d21367a.png)
 
Regards
maximspu

**Comment by jan-moxter** [comment]
Due to the reason that dynamic reports uses jasper report under the hood. Might that problem also exist there?

**Comment by maximspu** [comment]
I don't know it could also be a JasperReport bug, even if it seems strange to me, producing pdf from prints made in JasperReport I have never had a similar problem. Now I will do a test by producing the jrxml from the example above, with this I will make a print with JasperReport with the same data and check if the pdf gives me the same problem.

**Comment by maximspu** [comment]
It's a Jasper Report bug, I re-simulated everything with Jasper Studio.

Jrxml file obtained from the above example with the command .toJrXml (output) 
 

<?xml version="1.0" encoding="UTF-8"?>

<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="Report" pageWidth="595" pageHeight="842" whenNoDataType="NoPages" columnWidth="575" leftMargin="10" rightMargin="10" topMargin="10" bottomMargin="10" uuid="60f97a10-7db0-44ec-807f-13cbc79f303b">
	<style name="style_12_" forecolor="#000000" isBlankWhenNull="true" fontName="SansSerif" fontSize="10">
		<box topPadding="2" leftPadding="2" bottomPadding="2" rightPadding="2"/>
	</style>
	<style name="style_13_" isBlankWhenNull="true" fontName="Serif" fontSize="6">
		<box topPadding="2" leftPadding="2" bottomPadding="2" rightPadding="2">
			<topPen lineWidth="0.1" lineStyle="Solid"/>
			<leftPen lineWidth="0.1" lineStyle="Solid"/>
			<bottomPen lineWidth="0.1" lineStyle="Solid"/>
			<rightPen lineWidth="0.1" lineStyle="Solid"/>
		</box>
	</style>
	<field name="comments" class="java.util.List">
		<fieldDescription><![CDATA[comments]]></fieldDescription>
	</field>
	<columnHeader>
		<band height="17">
			<textField textAdjust="StretchHeight" isBlankWhenNull="true">
				<reportElement key="columnHeader.column_comments.title1" style="style_12_" positionType="Float" x="0" y="0" width="112" height="17" uuid="e0a87115-2801-47c7-8afa-f8b4eb07aa75"/>
				<textFieldExpression><![CDATA["prova"]]></textFieldExpression>
			</textField>
		</band>
	</columnHeader>
	<detail>
		<band height="12">
			<textField textAdjust="StretchHeight" isBlankWhenNull="true">
				<reportElement key="detail.column_comments1" style="style_13_" positionType="Float" x="0" y="0" width="112" height="12" uuid="83c3b0cd-5151-4af7-a566-b2e271e8be1f"/>
				<textElement textAlignment="Left"/>
				<textFieldExpression><![CDATA["aaaaaaaaaaa  bbbbbbbbbbbbb vvvvvvvvvvvvvvv ffffffff gggdfgegtrtyueee"]]></textFieldExpression>
			</textField>
		</band>
	</detail>
</jasperReport>

Result with jasper studio by performing the previuew of the print and printing the pdf:

![immagine](https://user-images.githubusercontent.com/74463405/100464415-dd0d5700-30cd-11eb-823c-7f2b2b458711.png)

**Comment by maximspu** [comment]
I also put this problem in the Jasper studio community, maybe someone will be able to tell us what caused the malfunction.

https://community.jaspersoft.com/questions/1174151/why-jasper-studios-pdf-preview-doesnt-print-last-line-completely

Regards

maximspu

**Comment by jan-moxter** [comment]
Awesome idea. Also if they have an idea what changes / updates to the jrxml might solve that issue, we could try to implement that in dynamicreports.
Please keep us updated

**Comment by maximspu** [comment]
I found out what caused the problem, it seems that the pdf print does not interpret the Serif font well, changing the font to Arial the pdf print works :-)

fontColumn.setFontName("Arial");

Regards
