### ISSUE TITLE
StretchWithOverflow removed. What is the alternative?

### ISSUE THREAD

**Issue by EPluribusUnum** [dynamicreports/dynamicreports#79]
In the latest version setting isStretchWithOverflow was removed.
Because of this xls/x reports were chaned. The long texts now overflow from the cells.
How can I control JasperReports isStretchWithOverflow flag OR how can I set a column/cell horizontal aligment to fill.

https://superuser.com/questions/507726/excel-prevent-cell-text-from-overflowing-into-next-empty-cell

Thank You!

**Comment by jan-moxter** [comment]
Hello, dynamicreports follows jasperreport. 
StretchwithOverflow is replaced by **textAdjust="StretchHeight"**  

 possible values: StretchHeight, ScaleFont, CutText

See also : http://jasperreports.sourceforge.net/sample.reference/stretch/index.html

or for dynamicreports field.setTextAdjust(TextAdjust enum)
