### ISSUE TITLE
How can I prevent long text overflow in xls/x?

### ISSUE THREAD

**Issue by EPluribusUnum** [dynamicreports/dynamicreports#80]
I wan to achieve this look.
![Want](https://user-images.githubusercontent.com/618980/101611901-5d0ab980-3a0a-11eb-9759-4e143f4c2211.png)

Text left aligned, date center aligned, numeric right aligned. Long text do not overflow from cell. Cell height is standard 1 row. Cell width is what I set from code. 
This was possible with older version. What should I set to get this result in the latest version?

STRETCH_HEIGHT messes up cell height, and long text overflow from cell
With CUT_TEXT the cell height and width is OK, but long text still overflow from cell. How can I prevent B column values to overflow to C column, when C it is empty?
![Current](https://user-images.githubusercontent.com/618980/101612141-9e02ce00-3a0a-11eb-9140-5388cb2d9c4c.png)

Thank You!

**Comment by srbala** [comment]
Its' Excel default behavior to show the overflow text when next cell is empty, nothing todo with dynamicreports or jasperreports.
