### ISSUE TITLE
itextpdf Upgrade?

### ISSUE THREAD

**Issue by ClancyDamon** [dynamicreports/dynamicreports#96]
We recently did a round of upgrading dependencies in our application, which included updating and replacing the old com.lowagie:itext with the newer com.itextpdf:itextpdf. Unfortunately, it looks like the DynamicReports still references com.lowagie. Any chance these references can be updated?

**Comment by jan-moxter** [comment]
itextpdf was used by the underlying jasperreport. the development branch does not use it any more
